### ISSUE TITLE
Allow more than 100 logs per run

### ISSUE THREAD

**Issue by selaux** [auth0-extensions/auth0-logs-to-logstash#2]
We want to use this extension to forward all Auth0 Logs to Logstash. Unfortunately we produce more logs than a job that runs 1 per minute and forwards 100 log entries can handle. Is it possible to increase this number to at least 10 times the amount of logs?

**Comment by sandrinodm** [comment]
This has been implemented in v2.0 - we see invocations that can transfer up to 20k of logs now.
