### ISSUE TITLE
Configuration Clarification

### ISSUE THREAD

**Issue by cLy-za** [auth0-extensions/auth0-logs-to-logstash#22]
Hi, 

I am able to connect to Logstash using the curl sample detailed in the readme, however when configuring the Auth0 extension, I am unable to successfully send logs. 

curl -H "content-type: application/json" -XPUT 'http://my-logstash.somewhere.io:1622' -d '{ "user" : "arcseldon", "post_date" : "2016-04-23T14:12:12", "message" : "Testing Auth0 integration with Elasticsearch" }'

My Logstash is hosted on AWS and I have tried opening it up to all web connections (tested with the curl request above from a public network) but am still unable to get the Auth0 extension working.

 I am inputting the LOGSTASH_URL as my-logstash.somewhere.io:1622 (so including the port) with the LOGSTASH_INDEX as auth0.

![image](https://user-images.githubusercontent.com/32568193/43464618-d7c7f8da-94db-11e8-8d0c-b5f01aa0ab49.png)

I have left the LOG_LEVEL and LOG_TYPES un-specified in the hopes that it will send all logs and have also white-listed all the Auth0 IPs for my tennant (Europe region) on the AWS Logstash load balancer.

![image](https://user-images.githubusercontent.com/32568193/43464642-e68c65d6-94db-11e8-82ae-e5a2d6a28b1b.png)

Jobs fail with the following error. I am wondering if anyone is able to suggest something that I am missing or if there is anything blatantly incorrect that I am doing in the configuration or something else I can try to get the connection working?

![image](https://user-images.githubusercontent.com/32568193/43464507-930f5b0c-94db-11e8-8304-ef9974733de4.png)

**Comment by fyockm** [comment]
@cLy-za with the `LOGSTASH_URL`, please include the protocol just as you did in the curl request: `http://my-logstash.somewhere.io:1622`

We will update the [extension docs](https://auth0.com/docs/extensions/logstash) with an example URL, so that this is more clear.

**Comment by cLy-za** [comment]
Hi, 

Thanks for the reply! We had tried using the protocol in the LOGSTASH_URL previously with the same results. We have also made sure all the auth0 ip addresses are allowed through our aws load balancer but that didn't seem to change anything either. I might just have to write a custom log scraper.

**Comment by jeffreyschultz** [comment]
Any update to this? We just got our proxy server setup to accept documents from the auth0 logstash plugin, and then I discover this issue.
