### ISSUE TITLE
X-API-Key header for token

### ISSUE THREAD

**Issue by jeffreyschultz** [auth0-extensions/auth0-logs-to-logstash#23]
We require an X-API-KEY token to be provided in order to get through our API gateway. How is the LOGSTASH_TOKEN provided in the request?

**Comment by zxan1285** [comment]
Hi @jeffreyschultz 
Extension is sending POST request to `${LOGSTASH_URL}?token=${LOGSTASH_TOKEN}`.
Currently extension does not support custom headers.
