### ISSUE TITLE
Non descript 500 errors

### ISSUE THREAD

**Issue by robgil** [auth0-extensions/auth0-logs-to-logstash#27]
Seeing 500 errors, but unsure of the root cause. 
```
checkpoint: null
start: 2019-01-23T13:07:01.715Z
end: null
logsProcessed: 0
error: {"name":"ManagementApiError","code":"Internal Server Error","message":"Internal Server Error","status":500}
```

**Comment by fyockm** [comment]
@robgil sorry, we would need more info to be able to investigate. 
is this the first time you set up the extension? was it working before?
what are the name of the tenant and region?

**Comment by robgil** [comment]
@fyockm brand new

**Comment by machuga** [comment]
Can you share your tenant and region with us?

**Comment by robgil** [comment]
@machuga I have an issue open id: 00422212. Lets chat there instead of  the public forum. We can use this issue to track error handling.

**Comment by fyockm** [comment]
Closing in favor of Support ticket
